prairie_teleop:
  ros__parameters:
    axis_left_x: 0
    axis_left_y: 1
    axis_right_x: 2
    button_a: 0
    button_b: 1
    button_x: 3
    button_y: 4
    button_lb: 6
    button_rb: 7
    vx_scale: 0.4
    vy_scale: -0.2
    yaw_rate_scale: -0.6
    deadzone: 0.1
